// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/ratelimit/v1/ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum to support multiple rate limiters
type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED    Algorithm = 0
	Algorithm_ALGORITHM_TOKEN_BUCKET   Algorithm = 1
	Algorithm_ALGORITHM_FIXED_WINDOW   Algorithm = 2
	Algorithm_ALGORITHM_SLIDING_WINDOW Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_TOKEN_BUCKET",
		2: "ALGORITHM_FIXED_WINDOW",
		3: "ALGORITHM_SLIDING_WINDOW",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED":    0,
		"ALGORITHM_TOKEN_BUCKET":   1,
		"ALGORITHM_FIXED_WINDOW":   2,
		"ALGORITHM_SLIDING_WINDOW": 3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ratelimit_v1_ratelimit_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_api_ratelimit_v1_ratelimit_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

// The incoming request (Matches your current RateRequest struct)
type IsAllowedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                          // e.g., "user_ip:192.168.1.1" or "{clientA:user1}"
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                     // Maximum allowed requests/tokens
	WindowMs      int64                  `protobuf:"varint,3,opt,name=window_ms,json=windowMs,proto3" json:"window_ms,omitempty"`               // Time window in milliseconds
	Algorithm     Algorithm              `protobuf:"varint,4,opt,name=algorithm,proto3,enum=ratelimit.v1.Algorithm" json:"algorithm,omitempty"` // Which algorithm the server should use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedRequest) Reset() {
	*x = IsAllowedRequest{}
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedRequest) ProtoMessage() {}

func (x *IsAllowedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedRequest.ProtoReflect.Descriptor instead.
func (*IsAllowedRequest) Descriptor() ([]byte, []int) {
	return file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *IsAllowedRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IsAllowedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *IsAllowedRequest) GetWindowMs() int64 {
	if x != nil {
		return x.WindowMs
	}
	return 0
}

func (x *IsAllowedRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

// The response back to the primary backend
type IsAllowedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"` // true if request should proceed, false if rate limited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedResponse) Reset() {
	*x = IsAllowedResponse{}
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedResponse) ProtoMessage() {}

func (x *IsAllowedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedResponse.ProtoReflect.Descriptor instead.
func (*IsAllowedResponse) Descriptor() ([]byte, []int) {
	return file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *IsAllowedResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_api_ratelimit_v1_ratelimit_proto protoreflect.FileDescriptor

const file_api_ratelimit_v1_ratelimit_proto_rawDesc = "" +
	"\n" +
	" api/ratelimit/v1/ratelimit.proto\x12\fratelimit.v1\"\x8e\x01\n" +
	"\x10IsAllowedRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1b\n" +
	"\twindow_ms\x18\x03 \x01(\x03R\bwindowMs\x125\n" +
	"\talgorithm\x18\x04 \x01(\x0e2\x17.ratelimit.v1.AlgorithmR\talgorithm\"-\n" +
	"\x11IsAllowedResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed*|\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALGORITHM_TOKEN_BUCKET\x10\x01\x12\x1a\n" +
	"\x16ALGORITHM_FIXED_WINDOW\x10\x02\x12\x1c\n" +
	"\x18ALGORITHM_SLIDING_WINDOW\x10\x032d\n" +
	"\x12RateLimiterService\x12N\n" +
	"\tIsAllowed\x12\x1e.ratelimit.v1.IsAllowedRequest\x1a\x1f.ratelimit.v1.IsAllowedResponse\"\x00B7Z5github.com/NirajDonga/rl/api/ratelimit/v1;ratelimitv1b\x06proto3"

var (
	file_api_ratelimit_v1_ratelimit_proto_rawDescOnce sync.Once
	file_api_ratelimit_v1_ratelimit_proto_rawDescData []byte
)

func file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP() []byte {
	file_api_ratelimit_v1_ratelimit_proto_rawDescOnce.Do(func() {
		file_api_ratelimit_v1_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ratelimit_v1_ratelimit_proto_rawDesc), len(file_api_ratelimit_v1_ratelimit_proto_rawDesc)))
	})
	return file_api_ratelimit_v1_ratelimit_proto_rawDescData
}

var file_api_ratelimit_v1_ratelimit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ratelimit_v1_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ratelimit_v1_ratelimit_proto_goTypes = []any{
	(Algorithm)(0),            // 0: ratelimit.v1.Algorithm
	(*IsAllowedRequest)(nil),  // 1: ratelimit.v1.IsAllowedRequest
	(*IsAllowedResponse)(nil), // 2: ratelimit.v1.IsAllowedResponse
}
var file_api_ratelimit_v1_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.v1.IsAllowedRequest.algorithm:type_name -> ratelimit.v1.Algorithm
	1, // 1: ratelimit.v1.RateLimiterService.IsAllowed:input_type -> ratelimit.v1.IsAllowedRequest
	2, // 2: ratelimit.v1.RateLimiterService.IsAllowed:output_type -> ratelimit.v1.IsAllowedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ratelimit_v1_ratelimit_proto_init() }
func file_api_ratelimit_v1_ratelimit_proto_init() {
	if File_api_ratelimit_v1_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ratelimit_v1_ratelimit_proto_rawDesc), len(file_api_ratelimit_v1_ratelimit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ratelimit_v1_ratelimit_proto_goTypes,
		DependencyIndexes: file_api_ratelimit_v1_ratelimit_proto_depIdxs,
		EnumInfos:         file_api_ratelimit_v1_ratelimit_proto_enumTypes,
		MessageInfos:      file_api_ratelimit_v1_ratelimit_proto_msgTypes,
	}.Build()
	File_api_ratelimit_v1_ratelimit_proto = out.File
	file_api_ratelimit_v1_ratelimit_proto_goTypes = nil
	file_api_ratelimit_v1_ratelimit_proto_depIdxs = nil
}
